project:
  type: website
  output-dir: _site

website:
  title: "Mavi, PhD"
  navbar:
    left:
      - href: portfolio.qmd
        text: Portfolio
      - href: blog.qmd
        text: Blog
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/rajinder-mavi/
      - icon: github
        href: https://github.com/rajindermavi
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    page-footer:
      left: |
        Having trouble? Try the backup site at 
        <a href="https://rajindermavi.github.io" target="_blank">https://rajindermavi.github.io</a>
    include-in-header: _includes/head.html


execute:
  freeze: auto

bibliography:
  - biblio/ab_testing.bib
  - biblio/general.bib
  - biblio/math.bib
  - biblio/ml.bib